'use strict';
function strip(sql){return sql.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/--.*$/gm,' ');}
function count(sql,re){return(sql.match(re)||[]).length;}
function collectSqlMetrics(sql,tokenize){
 const clean=strip(sql),upper=clean.toUpperCase();
 const tokens=tokenize?tokenize(sql):(clean.match(/`[^`]+`|'[^']*'|[A-Za-z_][A-Za-z0-9_$]*|\d+(?:\.\d+)?|[^\s]/g)||[]);
 const names=[];const re=/(?:^|,)\s*([A-Z_][A-Z0-9_]*)\s+AS\s*\(/gm;let m;const body=upper.slice(upper.indexOf('WITH')+4);while((m=re.exec(body)))names.push(m[1]);
 const featureChecks={WITH:/\bWITH\b/i.test(clean),LEFT_JOIN:/\bLEFT\s+JOIN\b/i.test(clean),UNION_ALL:/\bUNION\s+ALL\b/i.test(clean),ARRAY_AGG:/\bARRAY_AGG\s*\(/i.test(clean),UNNEST:/\bUNNEST\s*\(/i.test(clean),STRUCT:/\bSTRUCT\s*\(/i.test(clean),CASE:/\bCASE\b/i.test(clean),COALESCE:/\bCOALESCE\s*\(/i.test(clean),ROW_NUMBER:/\bROW_NUMBER\s*\(/i.test(clean),QUALIFY:/\bQUALIFY\b/i.test(clean),PIVOT:/\bPIVOT\s*\(/i.test(clean),EXISTS:/\bEXISTS\s*\(/i.test(clean),SELECT_STAR:/\bSELECT\s+\*/i.test(clean),EXCEPT:/\bEXCEPT\s*\(/i.test(clean),REPLACE:/\bREPLACE\s*\(/i.test(clean),WINDOW:/\bOVER\s*\(/i.test(clean)};
 return{sqlLines:sql.split(/\r?\n/).length,tokenCount:tokens.length,cteCount:names.length,cteNames:names,joinCount:count(upper,/\bJOIN\b/g),leftJoinCount:count(upper,/\bLEFT\s+JOIN\b/g),unionAllCount:count(upper,/\bUNION\s+ALL\b/g),pivotCount:count(upper,/\bPIVOT\s*\(/g),unnestCount:count(upper,/\bUNNEST\s*\(/g),caseCount:count(upper,/\bCASE\b/g),featureChecks};
}
function collectResultMetrics(result){const scopes=result.scopes||result.query_scopes||[];const outputs=result.output_lineages||result.outputs||[];const paths=result.lineage_paths||[];let scopeDepth=0,dependencyDepth=0;for(const s of scopes)scopeDepth=Math.max(scopeDepth,Number(s.scope_level||s.depth||0));for(const p of paths){const n=p.path||p.lineage_path||[];dependencyDepth=Math.max(dependencyDepth,Array.isArray(n)?n.length:String(n).split('->').length);}return{astNodes:Array.isArray(result.ast_nodes)?result.ast_nodes.length:null,scopeDepth,dependencyDepth,outputColumns:outputs.length};}
function verifyContract(s,r,c,connected){const f=[];const checks=[['SQL lines',s.sqlLines,c.minSqlLines],['Token count',s.tokenCount,c.minTokenCount],['CTE count',s.cteCount,c.minCteCount],['JOIN count',s.joinCount,c.minJoinCount]];if(connected)checks.push(['Output columns',r.outputColumns,c.minOutputColumns],['Dependency depth',r.dependencyDepth,c.minDependencyDepth]);for(const[x,a,m]of checks)if(a<m)f.push(`${x}: expected >= ${m}, actual ${a}`);for(const x of c.requiredFeatures)if(!s.featureChecks[x])f.push(`Required feature missing: ${x}`);return f;}
module.exports={collectSqlMetrics,collectResultMetrics,verifyContract};
